# Numpy practice session

In [1]:
# import this library in j. notebook
import numpy as np

# Creating an array using numpy

In [3]:
# 1D_array
import numpy as np
food= np.array(["samosa", "pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [10]:
price=np.array([10,15,120])
price

array([ 10,  15, 120])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [11]:
price[1]

15

In [15]:
food[0:2]

array(['samosa', 'pakora'], dtype='<U6')

In [16]:
price[0:]

array([ 10,  15, 120])

In [21]:
price[1:3]

array([ 15, 120])

In [22]:
price.mean()

48.333333333333336

In [28]:
price.argmax()

2

In [29]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
#Once
np.ones(4)

array([1., 1., 1., 1.])

In [34]:
# empty
np.empty(2)

array([ 8.09458208e+275, -1.00071931e-091])

In [35]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
# specify range
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
# table f 5
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [62]:
# line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
# specify your data
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [66]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array function

In [71]:
a= np.array([40,50,32,63,23.67,10.5,100,400])
a

array([ 40.  ,  50.  ,  32.  ,  63.  ,  23.67,  10.5 , 100.  , 400.  ])

In [72]:
a.sort()
a

array([ 10.5 ,  23.67,  32.  ,  40.  ,  50.  ,  63.  , 100.  , 400.  ])

In [73]:
b=np.array([10.4,45,60,7,80])
b

array([10.4, 45. , 60. ,  7. , 80. ])

In [80]:
c=np.concatenate((a,b))
c

array([ 10.5 ,  23.67,  32.  ,  40.  ,  50.  ,  63.  , 100.  , 400.  ,
        10.4 ,  45.  ,  60.  ,   7.  ,  80.  ])

In [81]:
c.sort()
c

array([  7.  ,  10.4 ,  10.5 ,  23.67,  32.  ,  40.  ,  45.  ,  50.  ,
        60.  ,  63.  ,  80.  , 100.  , 400.  ])

# 2-D Array

In [88]:
a= np.array([[1,2], [5,4]])
a

array([[1, 2],
       [5, 4]])

In [92]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [94]:
c=np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [97]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [98]:
d= np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
d

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [101]:
# to find the number of dimensions
d.ndim

3

In [102]:
d.size

24

In [103]:
d.shape 

(3, 2, 4)

In [ ]:
# d.shape(3 is length, 2 is row, and 4 is column)

In [104]:
a.size

4

In [106]:
e=np.arange(9) #3*3 
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
# reshape
g= e.reshape(3,3) #3*3=9
g 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# convert 1D into 2D

In [117]:
h= np.array([1,2,3,4,5,6,7,8,9])
h

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
h.shape

(9,)

In [119]:
# Rowwise 2D conversion

k=h[np.newaxis,:]
k

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [120]:
k.shape

(1, 9)

In [121]:
# column wise 2D conversion

l=h[:,np.newaxis]
l

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [126]:
s=np.array([1,2,3,4,5,6,7,8])
s

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
s*4

array([ 4,  8, 12, 16, 20, 24, 28, 32])

In [128]:
s+6

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [129]:
s/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [131]:
s.sum()

36

In [132]:
s.mean()

4.5